// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PamirPlastik.Persistence.Context;

#nullable disable

namespace PamirPlastik.Persistence.Migrations
{
    [DbContext(typeof(PamirPlastikContext))]
    partial class PamirPlastikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PamirPlastik.Domain.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description1_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description1_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighlightQuote_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighlightQuote_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.AboutFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<string>("Description_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueOrIcon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("AboutFeatures");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.AboutImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<string>("AltText_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltText_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("AboutImages");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowOnHome")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Color", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorID"));

                    b.Property<string>("HexCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_TR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorID");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<string>("Address_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneTitle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneTitle_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_TR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("ContactMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactMessageID"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactMessageID");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Fair", b =>
                {
                    b.Property<int>("FairID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FairID"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFuture")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stand")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FairID");

                    b.ToTable("Fairs");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.HomePageSetting", b =>
                {
                    b.Property<int>("HomePageSettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomePageSettingID"));

                    b.Property<string>("CatDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatTitleMain_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatTitleMain_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatTitleTop_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatTitleTop_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatalogPdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcomCommentCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcomDeliveryMonthly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcomStoreLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcomStoreScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportCountryCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FairDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FairDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FairTitleMain_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FairTitleMain_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FairTitleTop_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FairTitleTop_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatTitleMain_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatTitleMain_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatTitleTop_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatTitleTop_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobDealer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobExportCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobSectorYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroBadge1_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroBadge1_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroBadge2_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroBadge2_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroBadge3_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroBadge3_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitleMain_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitleMain_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitleTop_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitleTop_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem1Desc_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem1Desc_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem1Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem1Title_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem1Title_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem2Desc_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem2Desc_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem2Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem2Title_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem2Title_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem3Desc_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem3Desc_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem3Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem3Title_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdItem3Title_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdTitleMain_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdTitleMain_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdTitleTop_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdTitleTop_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeCount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HomePageSettingID");

                    b.ToTable("HomePageSettings");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("BoxCount")
                        .HasColumnType("int");

                    b.Property<string>("BoxSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("FullDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDishwasherSafe")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoodSafe")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug_TR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.ProductColor", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "ColorID");

                    b.HasIndex("ColorID");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageID"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.SocialMedia", b =>
                {
                    b.Property<int>("SocialMediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialMediaID"));

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlatformName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialMediaID");

                    b.ToTable("SocialMedias");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.AboutFeature", b =>
                {
                    b.HasOne("PamirPlastik.Domain.Entities.About", "About")
                        .WithMany("Features")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.AboutImage", b =>
                {
                    b.HasOne("PamirPlastik.Domain.Entities.About", "About")
                        .WithMany("Images")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Product", b =>
                {
                    b.HasOne("PamirPlastik.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.ProductColor", b =>
                {
                    b.HasOne("PamirPlastik.Domain.Entities.Color", "Color")
                        .WithMany("ProductColors")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PamirPlastik.Domain.Entities.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("PamirPlastik.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.About", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Color", b =>
                {
                    b.Navigation("ProductColors");
                });

            modelBuilder.Entity("PamirPlastik.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductColors");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
